version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u151-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mvn-dependencies-{{ checksum "pom.xml" }}
            - v1-mvn-dependencies-
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/main/frontend/package.json" }}
            - v1-dependencies-
      - run: mvn -B -Pfrontend -DskipTests package
      - persist_to_workspace:
          root: ~/project
          paths:
            - target/
            - src/main/frontend/
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          paths:
            - target/node
            - src/main/frontend/node_modules
          key: v1-dependencies-{{ checksum "src/main/frontend/package.json" }}
      - save_cache:
          paths:
            - ~/.m2
          key: v1-mvn-dependencies-{{ checksum "pom.xml" }}
  deploy-ui:
    docker:
      - image: circleci/node:10.5
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/main/frontend/package.json" }}
            - v1-dependencies-
      - run:
          name: Deploy UI Sample
          command: |
            cd src/main/frontend
            npm i
            cp now.json ../../../target/classes/frontend/
            cd ../../../target/classes/frontend
            ../../../src/main/frontend/node_modules/.bin/now -t ${NOW_TOKEN} -C --public --target production

workflows:
  version: 2
  default-workflow:
    jobs:
      - build
      - deploy-ui:
          requires:
            - build
